name: news_app
description: This app showcases clean architecture as proposed by Uncle Bob. The implementation comes from an article on Medium. https://devmuaz.medium.com/flutter-clean-architecture-series-part-1-d2d4c2e75c47
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  equatable: 1.2.5
  floor: 0.18.0
  flutter:
    sdk: flutter
  flutter_bloc: 6.1.1
  flutter_hooks: 0.15.0
  get_it: 5.0.3
  ionicons: 0.0.3
  retrofit: 1.3.4+1

dev_dependencies:
  build_runner: 1.10.11
  floor_generator: 0.18.0
  flutter_test:
    sdk: flutter
  lint: 1.0.0
  retrofit_generator: 1.4.1

flutter:
  uses-material-design: true































