name: news_app
description: This app showcases clean architecture as proposed by Uncle Bob. The implementation comes from an article on Medium. https://devmuaz.medium.com/flutter-clean-architecture-series-part-1-d2d4c2e75c47
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  equatable: 1.2.5
  floor: 0.18.0
  flutter:
    sdk: flutter
  flutter_bloc: 6.1.1
  flutter_hooks: 0.15.0
  get_it: 5.0.3
  ionicons: 0.0.3
  retrofit: 1.3.4+1

dev_dependencies:
  build_runner: 1.10.11
  floor_generator: 0.18.0
  flutter_test:
    sdk: flutter
  lint: 1.0.0
  retrofit_generator: 1.4.1

flutter:
  uses-material-design: true

  fonts:
    - family: Butler
      fonts:
        - asset: assets/fonts/butler/Butler_Ultra_Light.otf
          weight: 100
        - asset: assets/fonts/butler/Butler_Light.otf
          weight: 300
        - asset: assets/fonts/butler/Butler_Regular.otf
          weight: 400
        - asset: assets/fonts/butler/Butler_Medium.otf
          weight: 500
        - asset: assets/fonts/butler/Butler_Bold.otf
          weight: 700
        - asset: assets/fonts/butler/Butler_ExtraBold.otf
          weight: 800
        - asset: assets/fonts/butler/Butler_Black.otf
          weight: 900
    - family: Butler_Stencil
      fonts:
        - asset: assets/fonts/butler/Butler_Ultra_Light_Stencil.otf
          weight: 100
        - asset: assets/fonts/butler/Butler_Light_Stencil.otf
          weight: 300
        - asset: assets/fonts/butler/Butler_Regular_Stencil.otf
          weight: 400
        - asset: assets/fonts/butler/Butler_Medium_Stencil.otf
          weight: 500
        - asset: assets/fonts/butler/Butler_Bold_Stencil.otf
          weight: 700
        - asset: assets/fonts/butler/Butler_ExtraBold_Stencil.otf
          weight: 800
        - asset: assets/fonts/butler/Butler_Black_Stencil.otf
          weight: 900
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/plex_sans/IBMPlexSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/plex_sans/IBMPlexSans-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/plex_sans/IBMPlexSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/plex_sans/IBMPlexSans-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/plex_sans/IBMPlexSans-Light.ttf
          weight: 300
        - asset: assets/fonts/plex_sans/IBMPlexSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/plex_sans/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/plex_sans/IBMPlexSans-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/plex_sans/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/plex_sans/IBMPlexSans-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/plex_sans/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/plex_sans/IBMPlexSans-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/plex_sans/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/plex_sans/IBMPlexSans-BoldItalic.ttf
          style: italic
          weight: 700































